enable-magisk-update = true

[Facebook]
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"

[Messenger]
enabled = false
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"

[YouTube]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "both"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "both"

[Viber]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"
arch = "arm64-v8a"
build-mode = "both"
