enable-magisk-update = true

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"
build-mode = "both"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
build-mode = "both"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "both"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "both"

[Viber]
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"
arch = "arm64-v8a"
build-mode = "both"
