enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

[Messenger]
enabled = false
uptodown-dlurl = "https://facebook-messenger.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"

[Facebook]
uptodown-dlurl = "https://facebook.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"

[YouTube]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "both"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "both"

[SolidExplorer]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta/"
arch = "arm64-v8a"
build-mode = "both"

[Viber]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"
arch = "arm64-v8a"
build-mode = "both"
